FROM centos7.bmc
#RUN yum update -y && yum clean all
RUN yum install -y epel-release && yum clean all
RUN yum install -y wget bzip2 unzip patch make gcc-gfortran gcc-c++ blas-devel octave openblas && yum clean all
